Feature/cid 70/documentation for dev env
leanix/leanix-k8s-connector pull request #55
Opened 2021-05-19 01:54 UTC by aravindmetku

2021-05-19 07:34 UTC, dan-leanix requested changes
@aravindmetku You should not commit the files under `.idea` and also not the `.idea` folder itself.

2021-05-21 02:47 UTC, bharatpandiri approved these changes

2021-05-21 02:49 UTC, bharatpandiri commented
@dan-leanix Can you review the PR again and approve please ?

2021-05-26 06:30 UTC, bharatpandiri approved these changes

2021-05-26 06:31 UTC, bharatpandiri approved these changes

2021-05-26 06:37 UTC, merged